package com.yuan.im.netty.codec.online;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImResponseInfo.proto

public final class ImResponse {
  private ImResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImResponseInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImResponseInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImResponseInfo.DataType data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImResponseInfo.DataType data_type = 1;</code>
     */
    ImResponse.ImResponseInfo.DataType getDataType();

    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    boolean hasPullResponse();
    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    ImResponse.PullResponse getPullResponse();
    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    ImResponse.PullResponseOrBuilder getPullResponseOrBuilder();

    public ImResponse.ImResponseInfo.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   *protobuf 可以使用message 管理其他的message
   * </pre>
   *
   * Protobuf type {@code ImResponseInfo}
   */
  public  static final class ImResponseInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImResponseInfo)
      ImResponseInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImResponseInfo.newBuilder() to construct.
    private ImResponseInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImResponseInfo() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImResponseInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImResponseInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              ImResponse.PullResponse.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((ImResponse.PullResponse) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ImResponse.PullResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ImResponse.PullResponse) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImResponse.internal_static_ImResponseInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImResponse.internal_static_ImResponseInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImResponse.ImResponseInfo.class, ImResponse.ImResponseInfo.Builder.class);
    }

    /**
     * <pre>
     *定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code ImResponseInfo.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>PullResponseType = 0;</code>
       */
      PullResponseType(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>PullResponseType = 0;</code>
       */
      public static final int PullResponseType_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return PullResponseType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImResponse.ImResponseInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImResponseInfo.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      PULLRESPONSE(2),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return PULLRESPONSE;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImResponseInfo.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImResponseInfo.DataType data_type = 1;</code>
     */
    public ImResponse.ImResponseInfo.DataType getDataType() {
      @SuppressWarnings("deprecation")
      ImResponse.ImResponseInfo.DataType result = ImResponse.ImResponseInfo.DataType.valueOf(dataType_);
      return result == null ? ImResponse.ImResponseInfo.DataType.UNRECOGNIZED : result;
    }

    public static final int PULLRESPONSE_FIELD_NUMBER = 2;
    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    public boolean hasPullResponse() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    public ImResponse.PullResponse getPullResponse() {
      if (dataBodyCase_ == 2) {
         return (ImResponse.PullResponse) dataBody_;
      }
      return ImResponse.PullResponse.getDefaultInstance();
    }
    /**
     * <code>.PullResponse pullResponse = 2;</code>
     */
    public ImResponse.PullResponseOrBuilder getPullResponseOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (ImResponse.PullResponse) dataBody_;
      }
      return ImResponse.PullResponse.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != ImResponse.ImResponseInfo.DataType.PullResponseType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (ImResponse.PullResponse) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != ImResponse.ImResponseInfo.DataType.PullResponseType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ImResponse.PullResponse) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImResponse.ImResponseInfo)) {
        return super.equals(obj);
      }
      ImResponse.ImResponseInfo other = (ImResponse.ImResponseInfo) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getPullResponse()
              .equals(other.getPullResponse())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + PULLRESPONSE_FIELD_NUMBER;
          hash = (53 * hash) + getPullResponse().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImResponse.ImResponseInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.ImResponseInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.ImResponseInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImResponse.ImResponseInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImResponse.ImResponseInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImResponse.ImResponseInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImResponse.ImResponseInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobuf 可以使用message 管理其他的message
     * </pre>
     *
     * Protobuf type {@code ImResponseInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImResponseInfo)
        ImResponse.ImResponseInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImResponse.internal_static_ImResponseInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImResponse.internal_static_ImResponseInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImResponse.ImResponseInfo.class, ImResponse.ImResponseInfo.Builder.class);
      }

      // Construct using ImResponse.ImResponseInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImResponse.internal_static_ImResponseInfo_descriptor;
      }

      @java.lang.Override
      public ImResponse.ImResponseInfo getDefaultInstanceForType() {
        return ImResponse.ImResponseInfo.getDefaultInstance();
      }

      @java.lang.Override
      public ImResponse.ImResponseInfo build() {
        ImResponse.ImResponseInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImResponse.ImResponseInfo buildPartial() {
        ImResponse.ImResponseInfo result = new ImResponse.ImResponseInfo(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (pullResponseBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = pullResponseBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImResponse.ImResponseInfo) {
          return mergeFrom((ImResponse.ImResponseInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImResponse.ImResponseInfo other) {
        if (other == ImResponse.ImResponseInfo.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case PULLRESPONSE: {
            mergePullResponse(other.getPullResponse());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImResponse.ImResponseInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImResponse.ImResponseInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImResponseInfo.DataType data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImResponseInfo.DataType data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImResponseInfo.DataType data_type = 1;</code>
       */
      public ImResponse.ImResponseInfo.DataType getDataType() {
        @SuppressWarnings("deprecation")
        ImResponse.ImResponseInfo.DataType result = ImResponse.ImResponseInfo.DataType.valueOf(dataType_);
        return result == null ? ImResponse.ImResponseInfo.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImResponseInfo.DataType data_type = 1;</code>
       */
      public Builder setDataType(ImResponse.ImResponseInfo.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImResponseInfo.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ImResponse.PullResponse, ImResponse.PullResponse.Builder, ImResponse.PullResponseOrBuilder> pullResponseBuilder_;
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public boolean hasPullResponse() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public ImResponse.PullResponse getPullResponse() {
        if (pullResponseBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (ImResponse.PullResponse) dataBody_;
          }
          return ImResponse.PullResponse.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return pullResponseBuilder_.getMessage();
          }
          return ImResponse.PullResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public Builder setPullResponse(ImResponse.PullResponse value) {
        if (pullResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          pullResponseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public Builder setPullResponse(
          ImResponse.PullResponse.Builder builderForValue) {
        if (pullResponseBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          pullResponseBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public Builder mergePullResponse(ImResponse.PullResponse value) {
        if (pullResponseBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != ImResponse.PullResponse.getDefaultInstance()) {
            dataBody_ = ImResponse.PullResponse.newBuilder((ImResponse.PullResponse) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            pullResponseBuilder_.mergeFrom(value);
          }
          pullResponseBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public Builder clearPullResponse() {
        if (pullResponseBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          pullResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public ImResponse.PullResponse.Builder getPullResponseBuilder() {
        return getPullResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      public ImResponse.PullResponseOrBuilder getPullResponseOrBuilder() {
        if ((dataBodyCase_ == 2) && (pullResponseBuilder_ != null)) {
          return pullResponseBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (ImResponse.PullResponse) dataBody_;
          }
          return ImResponse.PullResponse.getDefaultInstance();
        }
      }
      /**
       * <code>.PullResponse pullResponse = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ImResponse.PullResponse, ImResponse.PullResponse.Builder, ImResponse.PullResponseOrBuilder> 
          getPullResponseFieldBuilder() {
        if (pullResponseBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = ImResponse.PullResponse.getDefaultInstance();
          }
          pullResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ImResponse.PullResponse, ImResponse.PullResponse.Builder, ImResponse.PullResponseOrBuilder>(
                  (ImResponse.PullResponse) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return pullResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImResponseInfo)
    }

    // @@protoc_insertion_point(class_scope:ImResponseInfo)
    private static final ImResponse.ImResponseInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImResponse.ImResponseInfo();
    }

    public static ImResponse.ImResponseInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImResponseInfo>
        PARSER = new com.google.protobuf.AbstractParser<ImResponseInfo>() {
      @java.lang.Override
      public ImResponseInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImResponseInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImResponseInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImResponseInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImResponse.ImResponseInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>int64 from = 1;</code>
     */
    long getFrom();

    /**
     * <pre>
     *目的群
     * </pre>
     *
     * <code>int64 group = 2;</code>
     */
    long getGroup();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *消息历史记录表中的消息编号
     * </pre>
     *
     * <code>int64 msgId = 4;</code>
     */
    long getMsgId();

    /**
     * <pre>
     *消息命令号
     * </pre>
     *
     * <code>int32 cmdId = 5;</code>
     */
    int getCmdId();

    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 sendTime = 6;</code>
     */
    long getSendTime();
  }
  /**
   * Protobuf type {@code PullResponse}
   */
  public  static final class PullResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PullResponse)
      PullResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullResponse.newBuilder() to construct.
    private PullResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullResponse() {
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PullResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              from_ = input.readInt64();
              break;
            }
            case 16: {

              group_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              msgId_ = input.readInt64();
              break;
            }
            case 40: {

              cmdId_ = input.readInt32();
              break;
            }
            case 48: {

              sendTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImResponse.internal_static_PullResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImResponse.internal_static_PullResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImResponse.PullResponse.class, ImResponse.PullResponse.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private long from_;
    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>int64 from = 1;</code>
     */
    public long getFrom() {
      return from_;
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private long group_;
    /**
     * <pre>
     *目的群
     * </pre>
     *
     * <code>int64 group = 2;</code>
     */
    public long getGroup() {
      return group_;
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSGID_FIELD_NUMBER = 4;
    private long msgId_;
    /**
     * <pre>
     *消息历史记录表中的消息编号
     * </pre>
     *
     * <code>int64 msgId = 4;</code>
     */
    public long getMsgId() {
      return msgId_;
    }

    public static final int CMDID_FIELD_NUMBER = 5;
    private int cmdId_;
    /**
     * <pre>
     *消息命令号
     * </pre>
     *
     * <code>int32 cmdId = 5;</code>
     */
    public int getCmdId() {
      return cmdId_;
    }

    public static final int SENDTIME_FIELD_NUMBER = 6;
    private long sendTime_;
    /**
     * <pre>
     *消息发送时间
     * </pre>
     *
     * <code>int64 sendTime = 6;</code>
     */
    public long getSendTime() {
      return sendTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0L) {
        output.writeInt64(1, from_);
      }
      if (group_ != 0L) {
        output.writeInt64(2, group_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (msgId_ != 0L) {
        output.writeInt64(4, msgId_);
      }
      if (cmdId_ != 0) {
        output.writeInt32(5, cmdId_);
      }
      if (sendTime_ != 0L) {
        output.writeInt64(6, sendTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, from_);
      }
      if (group_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, group_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (msgId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, msgId_);
      }
      if (cmdId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cmdId_);
      }
      if (sendTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sendTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImResponse.PullResponse)) {
        return super.equals(obj);
      }
      ImResponse.PullResponse other = (ImResponse.PullResponse) obj;

      if (getFrom()
          != other.getFrom()) return false;
      if (getGroup()
          != other.getGroup()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getMsgId()
          != other.getMsgId()) return false;
      if (getCmdId()
          != other.getCmdId()) return false;
      if (getSendTime()
          != other.getSendTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrom());
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGroup());
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + MSGID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMsgId());
      hash = (37 * hash) + CMDID_FIELD_NUMBER;
      hash = (53 * hash) + getCmdId();
      hash = (37 * hash) + SENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSendTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImResponse.PullResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.PullResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.PullResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.PullResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.PullResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImResponse.PullResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImResponse.PullResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImResponse.PullResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImResponse.PullResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImResponse.PullResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImResponse.PullResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImResponse.PullResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImResponse.PullResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullResponse)
        ImResponse.PullResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImResponse.internal_static_PullResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImResponse.internal_static_PullResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImResponse.PullResponse.class, ImResponse.PullResponse.Builder.class);
      }

      // Construct using ImResponse.PullResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0L;

        group_ = 0L;

        content_ = "";

        msgId_ = 0L;

        cmdId_ = 0;

        sendTime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImResponse.internal_static_PullResponse_descriptor;
      }

      @java.lang.Override
      public ImResponse.PullResponse getDefaultInstanceForType() {
        return ImResponse.PullResponse.getDefaultInstance();
      }

      @java.lang.Override
      public ImResponse.PullResponse build() {
        ImResponse.PullResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImResponse.PullResponse buildPartial() {
        ImResponse.PullResponse result = new ImResponse.PullResponse(this);
        result.from_ = from_;
        result.group_ = group_;
        result.content_ = content_;
        result.msgId_ = msgId_;
        result.cmdId_ = cmdId_;
        result.sendTime_ = sendTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImResponse.PullResponse) {
          return mergeFrom((ImResponse.PullResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImResponse.PullResponse other) {
        if (other == ImResponse.PullResponse.getDefaultInstance()) return this;
        if (other.getFrom() != 0L) {
          setFrom(other.getFrom());
        }
        if (other.getGroup() != 0L) {
          setGroup(other.getGroup());
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getMsgId() != 0L) {
          setMsgId(other.getMsgId());
        }
        if (other.getCmdId() != 0) {
          setCmdId(other.getCmdId());
        }
        if (other.getSendTime() != 0L) {
          setSendTime(other.getSendTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImResponse.PullResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImResponse.PullResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long from_ ;
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public long getFrom() {
        return from_;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public Builder setFrom(long value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0L;
        onChanged();
        return this;
      }

      private long group_ ;
      /**
       * <pre>
       *目的群
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public long getGroup() {
        return group_;
      }
      /**
       * <pre>
       *目的群
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public Builder setGroup(long value) {
        
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的群
       * </pre>
       *
       * <code>int64 group = 2;</code>
       */
      public Builder clearGroup() {
        
        group_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private long msgId_ ;
      /**
       * <pre>
       *消息历史记录表中的消息编号
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public long getMsgId() {
        return msgId_;
      }
      /**
       * <pre>
       *消息历史记录表中的消息编号
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public Builder setMsgId(long value) {
        
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息历史记录表中的消息编号
       * </pre>
       *
       * <code>int64 msgId = 4;</code>
       */
      public Builder clearMsgId() {
        
        msgId_ = 0L;
        onChanged();
        return this;
      }

      private int cmdId_ ;
      /**
       * <pre>
       *消息命令号
       * </pre>
       *
       * <code>int32 cmdId = 5;</code>
       */
      public int getCmdId() {
        return cmdId_;
      }
      /**
       * <pre>
       *消息命令号
       * </pre>
       *
       * <code>int32 cmdId = 5;</code>
       */
      public Builder setCmdId(int value) {
        
        cmdId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息命令号
       * </pre>
       *
       * <code>int32 cmdId = 5;</code>
       */
      public Builder clearCmdId() {
        
        cmdId_ = 0;
        onChanged();
        return this;
      }

      private long sendTime_ ;
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 sendTime = 6;</code>
       */
      public long getSendTime() {
        return sendTime_;
      }
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 sendTime = 6;</code>
       */
      public Builder setSendTime(long value) {
        
        sendTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息发送时间
       * </pre>
       *
       * <code>int64 sendTime = 6;</code>
       */
      public Builder clearSendTime() {
        
        sendTime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PullResponse)
    }

    // @@protoc_insertion_point(class_scope:PullResponse)
    private static final ImResponse.PullResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImResponse.PullResponse();
    }

    public static ImResponse.PullResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullResponse>
        PARSER = new com.google.protobuf.AbstractParser<PullResponse>() {
      @java.lang.Override
      public PullResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImResponse.PullResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImResponseInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImResponseInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PullResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ImResponseInfo.proto\"\222\001\n\016ImResponseInf" +
      "o\022+\n\tdata_type\030\001 \001(\0162\030.ImResponseInfo.Da" +
      "taType\022%\n\014pullResponse\030\002 \001(\0132\r.PullRespo" +
      "nseH\000\" \n\010DataType\022\024\n\020PullResponseType\020\000B" +
      "\n\n\010dataBody\"l\n\014PullResponse\022\014\n\004from\030\001 \001(" +
      "\003\022\r\n\005group\030\002 \001(\003\022\017\n\007content\030\003 \001(\t\022\r\n\005msg" +
      "Id\030\004 \001(\003\022\r\n\005cmdId\030\005 \001(\005\022\020\n\010sendTime\030\006 \001(" +
      "\003B\016B\nImResponseH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImResponseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImResponseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImResponseInfo_descriptor,
        new java.lang.String[] { "DataType", "PullResponse", "DataBody", });
    internal_static_PullResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PullResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PullResponse_descriptor,
        new java.lang.String[] { "From", "Group", "Content", "MsgId", "CmdId", "SendTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
