package com.yuan.im.netty.codec.online.vo;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ImRequestInfo.proto

public final class ImRequest {
  private ImRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImRequestInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImRequestInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImRequestInfo.DataType data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImRequestInfo.DataType data_type = 1;</code>
     */
    ImRequest.ImRequestInfo.DataType getDataType();

    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    boolean hasSendRequest();
    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    ImRequest.SendRequest getSendRequest();
    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    ImRequest.SendRequestOrBuilder getSendRequestOrBuilder();

    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    boolean hasPullRequest();
    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    ImRequest.PullRequest getPullRequest();
    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    ImRequest.PullRequestOrBuilder getPullRequestOrBuilder();

    public ImRequest.ImRequestInfo.DataBodyCase getDataBodyCase();
  }
  /**
   * <pre>
   *protobuf 可以使用message 管理其他的message
   * </pre>
   *
   * Protobuf type {@code ImRequestInfo}
   */
  public  static final class ImRequestInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImRequestInfo)
      ImRequestInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImRequestInfo.newBuilder() to construct.
    private ImRequestInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImRequestInfo() {
      dataType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImRequestInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImRequestInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              ImRequest.SendRequest.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((ImRequest.SendRequest) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ImRequest.SendRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ImRequest.SendRequest) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              ImRequest.PullRequest.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((ImRequest.PullRequest) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(ImRequest.PullRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((ImRequest.PullRequest) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImRequest.internal_static_ImRequestInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImRequest.internal_static_ImRequestInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImRequest.ImRequestInfo.class, ImRequest.ImRequestInfo.Builder.class);
    }

    /**
     * <pre>
     *定义一个枚举类型
     * </pre>
     *
     * Protobuf enum {@code ImRequestInfo.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>SendRequestType = 0;</code>
       */
      SendRequestType(0),
      /**
       * <code>PullRequestType = 1;</code>
       */
      PullRequestType(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       *在proto3 要求enum的编号从0开始
       * </pre>
       *
       * <code>SendRequestType = 0;</code>
       */
      public static final int SendRequestType_VALUE = 0;
      /**
       * <code>PullRequestType = 1;</code>
       */
      public static final int PullRequestType_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return SendRequestType;
          case 1: return PullRequestType;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return ImRequest.ImRequestInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:ImRequestInfo.DataType)
    }

    private int dataBodyCase_ = 0;
    private java.lang.Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      SENDREQUEST(2),
      PULLREQUEST(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return SENDREQUEST;
          case 3: return PULLREQUEST;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImRequestInfo.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *DataType自定义枚举类型，标识传的是哪一个枚举类型
     * </pre>
     *
     * <code>.ImRequestInfo.DataType data_type = 1;</code>
     */
    public ImRequest.ImRequestInfo.DataType getDataType() {
      @SuppressWarnings("deprecation")
      ImRequest.ImRequestInfo.DataType result = ImRequest.ImRequestInfo.DataType.valueOf(dataType_);
      return result == null ? ImRequest.ImRequestInfo.DataType.UNRECOGNIZED : result;
    }

    public static final int SENDREQUEST_FIELD_NUMBER = 2;
    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    public boolean hasSendRequest() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    public ImRequest.SendRequest getSendRequest() {
      if (dataBodyCase_ == 2) {
         return (ImRequest.SendRequest) dataBody_;
      }
      return ImRequest.SendRequest.getDefaultInstance();
    }
    /**
     * <code>.SendRequest sendRequest = 2;</code>
     */
    public ImRequest.SendRequestOrBuilder getSendRequestOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (ImRequest.SendRequest) dataBody_;
      }
      return ImRequest.SendRequest.getDefaultInstance();
    }

    public static final int PULLREQUEST_FIELD_NUMBER = 3;
    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    public boolean hasPullRequest() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    public ImRequest.PullRequest getPullRequest() {
      if (dataBodyCase_ == 3) {
         return (ImRequest.PullRequest) dataBody_;
      }
      return ImRequest.PullRequest.getDefaultInstance();
    }
    /**
     * <code>.PullRequest pullRequest = 3;</code>
     */
    public ImRequest.PullRequestOrBuilder getPullRequestOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (ImRequest.PullRequest) dataBody_;
      }
      return ImRequest.PullRequest.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != ImRequest.ImRequestInfo.DataType.SendRequestType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (ImRequest.SendRequest) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (ImRequest.PullRequest) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != ImRequest.ImRequestInfo.DataType.SendRequestType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (ImRequest.SendRequest) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (ImRequest.PullRequest) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImRequest.ImRequestInfo)) {
        return super.equals(obj);
      }
      ImRequest.ImRequestInfo other = (ImRequest.ImRequestInfo) obj;

      if (dataType_ != other.dataType_) return false;
      if (!getDataBodyCase().equals(other.getDataBodyCase())) return false;
      switch (dataBodyCase_) {
        case 2:
          if (!getSendRequest()
              .equals(other.getSendRequest())) return false;
          break;
        case 3:
          if (!getPullRequest()
              .equals(other.getPullRequest())) return false;
          break;
        case 0:
        default:
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + SENDREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getSendRequest().hashCode();
          break;
        case 3:
          hash = (37 * hash) + PULLREQUEST_FIELD_NUMBER;
          hash = (53 * hash) + getPullRequest().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImRequest.ImRequestInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.ImRequestInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.ImRequestInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.ImRequestInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImRequest.ImRequestInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.ImRequestInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImRequest.ImRequestInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *protobuf 可以使用message 管理其他的message
     * </pre>
     *
     * Protobuf type {@code ImRequestInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImRequestInfo)
        ImRequest.ImRequestInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImRequest.internal_static_ImRequestInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImRequest.internal_static_ImRequestInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImRequest.ImRequestInfo.class, ImRequest.ImRequestInfo.Builder.class);
      }

      // Construct using ImRequest.ImRequestInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImRequest.internal_static_ImRequestInfo_descriptor;
      }

      @java.lang.Override
      public ImRequest.ImRequestInfo getDefaultInstanceForType() {
        return ImRequest.ImRequestInfo.getDefaultInstance();
      }

      @java.lang.Override
      public ImRequest.ImRequestInfo build() {
        ImRequest.ImRequestInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImRequest.ImRequestInfo buildPartial() {
        ImRequest.ImRequestInfo result = new ImRequest.ImRequestInfo(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (sendRequestBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = sendRequestBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (pullRequestBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = pullRequestBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImRequest.ImRequestInfo) {
          return mergeFrom((ImRequest.ImRequestInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImRequest.ImRequestInfo other) {
        if (other == ImRequest.ImRequestInfo.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case SENDREQUEST: {
            mergeSendRequest(other.getSendRequest());
            break;
          }
          case PULLREQUEST: {
            mergePullRequest(other.getPullRequest());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImRequest.ImRequestInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImRequest.ImRequestInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private java.lang.Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImRequestInfo.DataType data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImRequestInfo.DataType data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImRequestInfo.DataType data_type = 1;</code>
       */
      public ImRequest.ImRequestInfo.DataType getDataType() {
        @SuppressWarnings("deprecation")
        ImRequest.ImRequestInfo.DataType result = ImRequest.ImRequestInfo.DataType.valueOf(dataType_);
        return result == null ? ImRequest.ImRequestInfo.DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImRequestInfo.DataType data_type = 1;</code>
       */
      public Builder setDataType(ImRequest.ImRequestInfo.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *DataType自定义枚举类型，标识传的是哪一个枚举类型
       * </pre>
       *
       * <code>.ImRequestInfo.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ImRequest.SendRequest, ImRequest.SendRequest.Builder, ImRequest.SendRequestOrBuilder> sendRequestBuilder_;
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public boolean hasSendRequest() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public ImRequest.SendRequest getSendRequest() {
        if (sendRequestBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (ImRequest.SendRequest) dataBody_;
          }
          return ImRequest.SendRequest.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return sendRequestBuilder_.getMessage();
          }
          return ImRequest.SendRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public Builder setSendRequest(ImRequest.SendRequest value) {
        if (sendRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          sendRequestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public Builder setSendRequest(
          ImRequest.SendRequest.Builder builderForValue) {
        if (sendRequestBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          sendRequestBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public Builder mergeSendRequest(ImRequest.SendRequest value) {
        if (sendRequestBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != ImRequest.SendRequest.getDefaultInstance()) {
            dataBody_ = ImRequest.SendRequest.newBuilder((ImRequest.SendRequest) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            sendRequestBuilder_.mergeFrom(value);
          }
          sendRequestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public Builder clearSendRequest() {
        if (sendRequestBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          sendRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public ImRequest.SendRequest.Builder getSendRequestBuilder() {
        return getSendRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      public ImRequest.SendRequestOrBuilder getSendRequestOrBuilder() {
        if ((dataBodyCase_ == 2) && (sendRequestBuilder_ != null)) {
          return sendRequestBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (ImRequest.SendRequest) dataBody_;
          }
          return ImRequest.SendRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.SendRequest sendRequest = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ImRequest.SendRequest, ImRequest.SendRequest.Builder, ImRequest.SendRequestOrBuilder> 
          getSendRequestFieldBuilder() {
        if (sendRequestBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = ImRequest.SendRequest.getDefaultInstance();
          }
          sendRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ImRequest.SendRequest, ImRequest.SendRequest.Builder, ImRequest.SendRequestOrBuilder>(
                  (ImRequest.SendRequest) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return sendRequestBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          ImRequest.PullRequest, ImRequest.PullRequest.Builder, ImRequest.PullRequestOrBuilder> pullRequestBuilder_;
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public boolean hasPullRequest() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public ImRequest.PullRequest getPullRequest() {
        if (pullRequestBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (ImRequest.PullRequest) dataBody_;
          }
          return ImRequest.PullRequest.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return pullRequestBuilder_.getMessage();
          }
          return ImRequest.PullRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public Builder setPullRequest(ImRequest.PullRequest value) {
        if (pullRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          pullRequestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public Builder setPullRequest(
          ImRequest.PullRequest.Builder builderForValue) {
        if (pullRequestBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          pullRequestBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public Builder mergePullRequest(ImRequest.PullRequest value) {
        if (pullRequestBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != ImRequest.PullRequest.getDefaultInstance()) {
            dataBody_ = ImRequest.PullRequest.newBuilder((ImRequest.PullRequest) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            pullRequestBuilder_.mergeFrom(value);
          }
          pullRequestBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public Builder clearPullRequest() {
        if (pullRequestBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          pullRequestBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public ImRequest.PullRequest.Builder getPullRequestBuilder() {
        return getPullRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      public ImRequest.PullRequestOrBuilder getPullRequestOrBuilder() {
        if ((dataBodyCase_ == 3) && (pullRequestBuilder_ != null)) {
          return pullRequestBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (ImRequest.PullRequest) dataBody_;
          }
          return ImRequest.PullRequest.getDefaultInstance();
        }
      }
      /**
       * <code>.PullRequest pullRequest = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ImRequest.PullRequest, ImRequest.PullRequest.Builder, ImRequest.PullRequestOrBuilder> 
          getPullRequestFieldBuilder() {
        if (pullRequestBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = ImRequest.PullRequest.getDefaultInstance();
          }
          pullRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ImRequest.PullRequest, ImRequest.PullRequest.Builder, ImRequest.PullRequestOrBuilder>(
                  (ImRequest.PullRequest) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return pullRequestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImRequestInfo)
    }

    // @@protoc_insertion_point(class_scope:ImRequestInfo)
    private static final ImRequest.ImRequestInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImRequest.ImRequestInfo();
    }

    public static ImRequest.ImRequestInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImRequestInfo>
        PARSER = new com.google.protobuf.AbstractParser<ImRequestInfo>() {
      @java.lang.Override
      public ImRequestInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImRequestInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImRequestInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImRequestInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImRequest.ImRequestInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SendRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SendRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>int64 from = 1;</code>
     */
    long getFrom();

    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    java.lang.String getGroup();
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    java.lang.String getContent();
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <pre>
     *0文字 1文件
     * </pre>
     *
     * <code>int32 type = 4;</code>
     */
    int getType();

    /**
     * <pre>
     *0建立连接，1正常发送消息，2心跳检测，3ack
     * </pre>
     *
     * <code>int32 cmd = 5;</code>
     */
    int getCmd();
  }
  /**
   * Protobuf type {@code SendRequest}
   */
  public  static final class SendRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SendRequest)
      SendRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SendRequest.newBuilder() to construct.
    private SendRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SendRequest() {
      group_ = "";
      content_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SendRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SendRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              from_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 32: {

              type_ = input.readInt32();
              break;
            }
            case 40: {

              cmd_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImRequest.internal_static_SendRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImRequest.internal_static_SendRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImRequest.SendRequest.class, ImRequest.SendRequest.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private long from_;
    /**
     * <pre>
     *发送者
     * </pre>
     *
     * <code>int64 from = 1;</code>
     */
    public long getFrom() {
      return from_;
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object group_;
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile java.lang.Object content_;
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *消息内容
     * </pre>
     *
     * <code>string content = 3;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <pre>
     *0文字 1文件
     * </pre>
     *
     * <code>int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    public static final int CMD_FIELD_NUMBER = 5;
    private int cmd_;
    /**
     * <pre>
     *0建立连接，1正常发送消息，2心跳检测，3ack
     * </pre>
     *
     * <code>int32 cmd = 5;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != 0L) {
        output.writeInt64(1, from_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (type_ != 0) {
        output.writeInt32(4, type_);
      }
      if (cmd_ != 0) {
        output.writeInt32(5, cmd_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, from_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (type_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImRequest.SendRequest)) {
        return super.equals(obj);
      }
      ImRequest.SendRequest other = (ImRequest.SendRequest) obj;

      if (getFrom()
          != other.getFrom()) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (getType()
          != other.getType()) return false;
      if (getCmd()
          != other.getCmd()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFrom());
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImRequest.SendRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.SendRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.SendRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.SendRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.SendRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.SendRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.SendRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.SendRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.SendRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImRequest.SendRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.SendRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.SendRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImRequest.SendRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SendRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SendRequest)
        ImRequest.SendRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImRequest.internal_static_SendRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImRequest.internal_static_SendRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImRequest.SendRequest.class, ImRequest.SendRequest.Builder.class);
      }

      // Construct using ImRequest.SendRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        from_ = 0L;

        group_ = "";

        content_ = "";

        type_ = 0;

        cmd_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImRequest.internal_static_SendRequest_descriptor;
      }

      @java.lang.Override
      public ImRequest.SendRequest getDefaultInstanceForType() {
        return ImRequest.SendRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ImRequest.SendRequest build() {
        ImRequest.SendRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImRequest.SendRequest buildPartial() {
        ImRequest.SendRequest result = new ImRequest.SendRequest(this);
        result.from_ = from_;
        result.group_ = group_;
        result.content_ = content_;
        result.type_ = type_;
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImRequest.SendRequest) {
          return mergeFrom((ImRequest.SendRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImRequest.SendRequest other) {
        if (other == ImRequest.SendRequest.getDefaultInstance()) return this;
        if (other.getFrom() != 0L) {
          setFrom(other.getFrom());
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (other.getType() != 0) {
          setType(other.getType());
        }
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImRequest.SendRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImRequest.SendRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long from_ ;
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public long getFrom() {
        return from_;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public Builder setFrom(long value) {
        
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发送者
       * </pre>
       *
       * <code>int64 from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *消息内容
       * </pre>
       *
       * <code>string content = 3;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <pre>
       *0文字 1文件
       * </pre>
       *
       * <code>int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *0文字 1文件
       * </pre>
       *
       * <code>int32 type = 4;</code>
       */
      public Builder setType(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0文字 1文件
       * </pre>
       *
       * <code>int32 type = 4;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *0建立连接，1正常发送消息，2心跳检测，3ack
       * </pre>
       *
       * <code>int32 cmd = 5;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *0建立连接，1正常发送消息，2心跳检测，3ack
       * </pre>
       *
       * <code>int32 cmd = 5;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0建立连接，1正常发送消息，2心跳检测，3ack
       * </pre>
       *
       * <code>int32 cmd = 5;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SendRequest)
    }

    // @@protoc_insertion_point(class_scope:SendRequest)
    private static final ImRequest.SendRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImRequest.SendRequest();
    }

    public static ImRequest.SendRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SendRequest>
        PARSER = new com.google.protobuf.AbstractParser<SendRequest>() {
      @java.lang.Override
      public SendRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SendRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SendRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SendRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImRequest.SendRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PullRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PullRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用户id（是获取一个用户的所有会话的历史记录，还是一个会话的历史记录）
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     */
    long getUid();

    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    java.lang.String getGroup();
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    com.google.protobuf.ByteString
        getGroupBytes();

    /**
     * <pre>
     *拉取历史记录的起始位置，初始是0，之后用服务器返回的数据
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     */
    long getOffset();

    /**
     * <pre>
     *单次拉
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     */
    int getLimit();
  }
  /**
   * Protobuf type {@code PullRequest}
   */
  public  static final class PullRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PullRequest)
      PullRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PullRequest.newBuilder() to construct.
    private PullRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PullRequest() {
      group_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PullRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PullRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              uid_ = input.readInt64();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              group_ = s;
              break;
            }
            case 24: {

              offset_ = input.readInt64();
              break;
            }
            case 32: {

              limit_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ImRequest.internal_static_PullRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ImRequest.internal_static_PullRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ImRequest.PullRequest.class, ImRequest.PullRequest.Builder.class);
    }

    public static final int UID_FIELD_NUMBER = 1;
    private long uid_;
    /**
     * <pre>
     *用户id（是获取一个用户的所有会话的历史记录，还是一个会话的历史记录）
     * </pre>
     *
     * <code>int64 uid = 1;</code>
     */
    public long getUid() {
      return uid_;
    }

    public static final int GROUP_FIELD_NUMBER = 2;
    private volatile java.lang.Object group_;
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *目的会话
     * </pre>
     *
     * <code>string group = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 3;
    private long offset_;
    /**
     * <pre>
     *拉取历史记录的起始位置，初始是0，之后用服务器返回的数据
     * </pre>
     *
     * <code>int64 offset = 3;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int LIMIT_FIELD_NUMBER = 4;
    private int limit_;
    /**
     * <pre>
     *单次拉
     * </pre>
     *
     * <code>int32 limit = 4;</code>
     */
    public int getLimit() {
      return limit_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (uid_ != 0L) {
        output.writeInt64(1, uid_);
      }
      if (!getGroupBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, group_);
      }
      if (offset_ != 0L) {
        output.writeInt64(3, offset_);
      }
      if (limit_ != 0) {
        output.writeInt32(4, limit_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (uid_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, uid_);
      }
      if (!getGroupBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, group_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, offset_);
      }
      if (limit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, limit_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ImRequest.PullRequest)) {
        return super.equals(obj);
      }
      ImRequest.PullRequest other = (ImRequest.PullRequest) obj;

      if (getUid()
          != other.getUid()) return false;
      if (!getGroup()
          .equals(other.getGroup())) return false;
      if (getOffset()
          != other.getOffset()) return false;
      if (getLimit()
          != other.getLimit()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUid());
      hash = (37 * hash) + GROUP_FIELD_NUMBER;
      hash = (53 * hash) + getGroup().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + LIMIT_FIELD_NUMBER;
      hash = (53 * hash) + getLimit();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ImRequest.PullRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.PullRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.PullRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.PullRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.PullRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ImRequest.PullRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ImRequest.PullRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.PullRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.PullRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ImRequest.PullRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ImRequest.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ImRequest.PullRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ImRequest.PullRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PullRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PullRequest)
        ImRequest.PullRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ImRequest.internal_static_PullRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ImRequest.internal_static_PullRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ImRequest.PullRequest.class, ImRequest.PullRequest.Builder.class);
      }

      // Construct using ImRequest.PullRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uid_ = 0L;

        group_ = "";

        offset_ = 0L;

        limit_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ImRequest.internal_static_PullRequest_descriptor;
      }

      @java.lang.Override
      public ImRequest.PullRequest getDefaultInstanceForType() {
        return ImRequest.PullRequest.getDefaultInstance();
      }

      @java.lang.Override
      public ImRequest.PullRequest build() {
        ImRequest.PullRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ImRequest.PullRequest buildPartial() {
        ImRequest.PullRequest result = new ImRequest.PullRequest(this);
        result.uid_ = uid_;
        result.group_ = group_;
        result.offset_ = offset_;
        result.limit_ = limit_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ImRequest.PullRequest) {
          return mergeFrom((ImRequest.PullRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ImRequest.PullRequest other) {
        if (other == ImRequest.PullRequest.getDefaultInstance()) return this;
        if (other.getUid() != 0L) {
          setUid(other.getUid());
        }
        if (!other.getGroup().isEmpty()) {
          group_ = other.group_;
          onChanged();
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getLimit() != 0) {
          setLimit(other.getLimit());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ImRequest.PullRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ImRequest.PullRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long uid_ ;
      /**
       * <pre>
       *用户id（是获取一个用户的所有会话的历史记录，还是一个会话的历史记录）
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       */
      public long getUid() {
        return uid_;
      }
      /**
       * <pre>
       *用户id（是获取一个用户的所有会话的历史记录，还是一个会话的历史记录）
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       */
      public Builder setUid(long value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *用户id（是获取一个用户的所有会话的历史记录，还是一个会话的历史记录）
       * </pre>
       *
       * <code>int64 uid = 1;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object group_ = "";
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public java.lang.String getGroup() {
        java.lang.Object ref = group_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          group_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGroupBytes() {
        java.lang.Object ref = group_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          group_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder setGroup(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        group_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder clearGroup() {
        
        group_ = getDefaultInstance().getGroup();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *目的会话
       * </pre>
       *
       * <code>string group = 2;</code>
       */
      public Builder setGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        group_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <pre>
       *拉取历史记录的起始位置，初始是0，之后用服务器返回的数据
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <pre>
       *拉取历史记录的起始位置，初始是0，之后用服务器返回的数据
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *拉取历史记录的起始位置，初始是0，之后用服务器返回的数据
       * </pre>
       *
       * <code>int64 offset = 3;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private int limit_ ;
      /**
       * <pre>
       *单次拉
       * </pre>
       *
       * <code>int32 limit = 4;</code>
       */
      public int getLimit() {
        return limit_;
      }
      /**
       * <pre>
       *单次拉
       * </pre>
       *
       * <code>int32 limit = 4;</code>
       */
      public Builder setLimit(int value) {
        
        limit_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *单次拉
       * </pre>
       *
       * <code>int32 limit = 4;</code>
       */
      public Builder clearLimit() {
        
        limit_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PullRequest)
    }

    // @@protoc_insertion_point(class_scope:PullRequest)
    private static final ImRequest.PullRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ImRequest.PullRequest();
    }

    public static ImRequest.PullRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PullRequest>
        PARSER = new com.google.protobuf.AbstractParser<PullRequest>() {
      @java.lang.Override
      public PullRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PullRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PullRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PullRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ImRequest.PullRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImRequestInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImRequestInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SendRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SendRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PullRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PullRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ImRequestInfo.proto\"\307\001\n\rImRequestInfo\022" +
      "*\n\tdata_type\030\001 \001(\0162\027.ImRequestInfo.DataT" +
      "ype\022#\n\013sendRequest\030\002 \001(\0132\014.SendRequestH\000" +
      "\022#\n\013pullRequest\030\003 \001(\0132\014.PullRequestH\000\"4\n" +
      "\010DataType\022\023\n\017SendRequestType\020\000\022\023\n\017PullRe" +
      "questType\020\001B\n\n\010dataBody\"V\n\013SendRequest\022\014" +
      "\n\004from\030\001 \001(\003\022\r\n\005group\030\002 \001(\t\022\017\n\007content\030\003" +
      " \001(\t\022\014\n\004type\030\004 \001(\005\022\013\n\003cmd\030\005 \001(\005\"H\n\013PullR" +
      "equest\022\013\n\003uid\030\001 \001(\003\022\r\n\005group\030\002 \001(\t\022\016\n\006of" +
      "fset\030\003 \001(\003\022\r\n\005limit\030\004 \001(\005B\rB\tImRequestH\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImRequestInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImRequestInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImRequestInfo_descriptor,
        new java.lang.String[] { "DataType", "SendRequest", "PullRequest", "DataBody", });
    internal_static_SendRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SendRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SendRequest_descriptor,
        new java.lang.String[] { "From", "Group", "Content", "Type", "Cmd", });
    internal_static_PullRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_PullRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PullRequest_descriptor,
        new java.lang.String[] { "Uid", "Group", "Offset", "Limit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
